### ISSUE TITLE
[Bug report] Data type is repeated in default values

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2427] opened 2024-03-05 06:06 UTC
### Version

main branch

### Describe what's wrong

An example, you can see the column is of type varchar(100) and the default value for that column is also varchar(100). Does this information need to be repeated?

```json
{"code":0,"table":{"name":"new_departments","columns":[{"name":"department_id","type":"integer","nullable":false,"autoIncrement":false},{"name":"department_name","type":"varchar(100)","nullable":true,"autoIncrement":false,"defaultValue":{"type":"literal","dataType":"varchar(100)","value":"Unknown"}}],"properties":{},"audit":{},"distribution":{"strategy":"none","number":0,"funcArgs":[]},"sortOrders":[],"partitioning":[],"indexes":[]}}%   
```
### Error message and/or stacktrace

N/A

### How to reproduce

Start up the playground. Run this SQL:
```SQL
create table hr.new_departments (
    department_id int4 NOT NULL,
    department_name varchar(100) default 'Unknown'
);
```

Get the information via the REST interface:
```shell
 curl http://localhost:8090/api/metalakes/metalake_demo/catalogs/catalog_postgres/schemas/hr/tables/new_departments
```

**Comment by mchades** [comment] 2024-03-05 06:23
It's not a bug. Since the default value is a Literal, we need to determine its datatype. For instance, for the value "20230101," it could be an `integer`, `varchar`, or `date`.

**Comment by mchades** [comment] 2024-03-05 06:24
FYI:
https://datastrato.ai/docs/0.4.0/manage-metadata-using-gravitino#table-column-default-value

**Comment by mchades** [comment] 2024-08-01 12:42
@justinmclean I'm going to close this issue, if you still have questions after reading the explanation above, please leave a message or open the issue again.

**Closed by mchades** 2024-08-01 12:42 UTC
Labels: bug, 0.6.0
