### ISSUE TITLE
[Subtask] Refactor the `getFileLocation` logic in the Python GVFS

### ISSUE THREAD

**Issue by xloya** [apache/gravitino#4280] opened 2024-07-26 01:44 UTC
### Describe the subtask

Refactor the logic of getting the file location in Python GVFS and move some of the checking logic to the server.

### Parent issue

#4021

**Comment by xunliu** [comment] 2024-08-05 04:00
This issue is a duplicate of #4278, so I'm closed.

**Closed** 2024-10-08 11:00 UTC
Labels: subtask
