### ISSUE TITLE
[Bug report] sometimes report kerberos login fail

### ISSUE THREAD

**Issue by mygrsun** [apache/gravitino#3822] opened 2024-06-07 11:06 UTC
### Version
0.5.1

### Describe what's wrong

![image](https://github.com/datastrato/gravitino/assets/4070282/4593272f-5070-4e3e-9f61-62a77339a1df)
![image](https://github.com/datastrato/gravitino/assets/4070282/28910773-388e-402d-9bd4-aa3ec8ae1bb5)

the log displays key is at /keytabs/gravitino-2427332928364083481-keytab 
but the /keytabs/ dir is empty

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/4070282/3a48592d-099b-48b5-a45e-fcf9317bc5ae)

### How to reproduce

0.5.1

**Comment by yuqi1129** [comment] 2024-06-07 13:00
@mygrsun 

Can you provide more information so we can reproduce it locally?

**Comment by mygrsun** [comment] 2024-06-09 02:30
> @mygrsun
> 
> Can you provide more information so we can reproduce it locally?

The phonomenon I see is that report that error and the keytab disappeared.

reproduce way is:
1、make a hive catalog with kerberos
2、runing for a day
3、sometimes the error will appear

I have encountered twice,so far. in 0.5.1
It is a very fatal bug.

**Comment by yuqi1129** [comment] 2024-10-29 13:23
Can't reproduced locally,  close it temporarily and please reopen it when more information was provided.

**Closed by yuqi1129** 2024-10-29 13:23 UTC
Labels: bug
