### ISSUE TITLE
[Improvement] Add the out direcotory in the project to the git ignore file

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4234] opened 2024-07-22 10:57 UTC
### What would you like to be improved?

After we build Gravitino, there will be some `out` directory under the project folder, please see:
<img width="767" alt="image" src="https://github.com/user-attachments/assets/542f65ca-322b-4b41-80e6-ec833b600c94">

### How should we improve?

Add them to the .gitignore file or avoid generating such files.

**Comment by four1er** [comment] 2024-07-22 17:22
hello, I want to solve this issue. Please assign it to me, thanks!

**Comment by justinmclean** [comment] 2024-07-29 06:06
@four1er do you still want to work on this?

**Comment by khmgobe** [comment] 2024-07-29 09:20
@justinmclean If possible, can I try it?

**Comment by yuqi1129** [comment] 2024-07-29 11:16
It seems that we can't reproduce the issue in the main branch.

**Comment by justinmclean** [comment] 2024-08-01 03:32
Closing as we can't reproduce, please ask to reopen if you come across the issue again.

**Closed by justinmclean** 2024-08-01 03:32 UTC
Labels: good first issue, help wanted, improvement
