### ISSUE TITLE
[FEATURE] create/drop catalog via native syntax in Trino connector

### ISSUE THREAD

**Issue by xiacongling** [apache/gravitino#2432] opened 2024-03-05 07:50 UTC
### Describe the feature

since version 408, Trino can do catalog management via [`CREATE CATALOG` and `DROP CATALOG` syntax](https://github.com/trinodb/trino/pull/13931). 

### Motivation

Gravitino's doc says:

[> Trino itself does not support creating catalogs](https://github.com/datastrato/gravitino/blob/49bacdf2a7f3d5c417412866063234773918d2ff/docs/trino-connector/supported-catalog.md?plain=1#L18)

but actually, Trino now support catalog management via create/drop catalog syntax.

### Describe the solution

1. fix document
2. can we use native SQL syntax to manage catalogs via Trino connector?

**Comment by diqiu50** [comment] 2024-03-05 08:16
Thank you @xiacongling 
Do you have any idea to implement catalog operations through the CREATE CATALOG and DROP CATALOG commands? Currently, Trino does not pass the CREATE CATALOG command to the connector for us to handle

**Comment by diqiu50** [comment] 2024-08-01 13:17
Duplicate of #3632

**Closed** 2024-08-01 13:17 UTC
Labels: feature
