### ISSUE TITLE
[Bug report]Case sensitive issue when list schema in iceberg catalog

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#1853] opened 2024-02-01 10:57 UTC
### Version

main branch

### Describe what's wrong

<img width="655" alt="截屏2024-02-01 18 40 28" src="https://github.com/datastrato/gravitino/assets/154112360/88671f0d-6983-44ec-9b4e-b9583292079e">
<img width="526" alt="截屏2024-02-01 18 40 58" src="https://github.com/datastrato/gravitino/assets/154112360/ce66c0a4-13dd-46ee-954c-69e6fb6b251b">

### Error message and/or stacktrace

N/A

### How to reproduce

1. create schema with upper case name in api
2. create table under the schema in trino, fill in the api path parameter with the schema lower case name
3. list schema in api
4. show schemas under catalog in trino
5. the result are different

**Comment by yuqi1129** [comment] 2024-02-01 11:21
> create schema with upper case name
create table under the schema, fill in the api path parameter with the schema lower case name
list schema in api
show schemas under catalog in trino
the result are different


@danhuawang Can you give detailed information and steps so that I can reproduce it locally, I have checked the steps you mentioned, but everything seems fine for me.

**Comment by danhuawang** [comment] 2024-02-02 03:18
> * create schema with upper case name in api
> * create table under the schema in trino, fill in the api path parameter with the schema lower case name

create schema with upper case name in api
create table under the schema in trino, using the schema lower case name

**Comment by yuqi1129** [comment] 2024-02-04 03:52
@danhuawang 
This is a bug caused by Trino and Iceberg.
1. Create an upper case schema (database) through Gravitino server. 
2. Using the database in Trino, Trino is case-insensitive, so it will display the name as lowercase.
3. Creating a table under this schema through Trino, then
4. The Gravitino server will Iceberg API to create table, the database passed to the Gravitino server is lowercase, due to the logic
![image](https://github.com/datastrato/gravitino/assets/15794564/e3baafc4-d94c-4a31-b8bd-c42899392bae)
and MySQL is case-insensitive in like condition, so it will call the following code to create table

<img width="1485" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/591af3ff-480b-4b62-840b-49f069a0f5a9">

Then Iceberg will create a new schema in lowercase.

**Comment by yuqi1129** [comment] 2024-02-04 03:53
@FANNG1 
We should work together to resolve this issue.

**Comment by danhuawang** [comment] 2024-02-04 11:28
Another scenerio:  rename catalog name from lower case to upper case in UI, then go to trino to create schema ,encounter  catalog not exist issue.


trino> show catalogs;
          Catalog           
----------------------------
 gravitino                  
 jmx                        
 memory                     
 metalake_demo.CATALOG_HIVE 
 metalake_demo.ICE1         
 system                     
 tpcds                      
 tpch                       
(8 rows)

Query 20240204_111303_00013_h2i2r, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.05 [0 rows, 0B] [0 rows/s, 0B/s]

trino> CREATE SCHEMA "metalake_demo.CATALOG_HIVE".database_01;
Query 20240204_111759_00014_h2i2r failed: line 1:1: Catalog 'metalake_demo.catalog_hive' does not exist
CREATE SCHEMA "metalake_demo.CATALOG_HIVE".database_01

trino> CREATE SCHEMA "metalake_demo.catalog_hive".database_01;
Query 20240204_111848_00015_h2i2r failed: line 1:1: Catalog 'metalake_demo.catalog_hive' does not exist
CREATE SCHEMA "metalake_demo.catalog_hive".database_01

**Comment by yuqi1129** [comment] 2024-04-16 03:39
This issue is because Trino will convert all schema names to lower case and there will be case-related issues between Gravitino and Trino. Since it's Trino's internal logic, I'm afraid it can't be fixed in a short time. 

What's your opinion?
@diqiu50

**Comment by diqiu50** [comment] 2024-08-01 12:44
We don't need to fix it. When users are using Trino, they should be aware of this issue when naming tables or schemas

**Closed** 2024-08-01 12:54 UTC
Labels: bug, 0.6.0
